"""empty message

Revision ID: 849495db5117
Revises: d32de89c3bde
Create Date: 2025-10-14 22:07:38.073083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '849495db5117'
down_revision = 'd32de89c3bde'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qr_code_base64', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('quiz_url_cached', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('qr_generated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('difficulty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quizzes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficulty', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_column('qr_generated_at')
        batch_op.drop_column('quiz_url_cached')
        batch_op.drop_column('qr_code_base64')

    # ### end Alembic commands ###
