"""Add image_mobile to Banner model

Revision ID: ba0f15375c0b
Revises: c67226e904c8
Create Date: 2025-10-15 09:58:02.067697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba0f15375c0b'
down_revision = 'c67226e904c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_mobile', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('banners', schema=None) as batch_op:
        batch_op.drop_column('image_mobile')

    # ### end Alembic commands ###
